version: '3.8'

services:
  app:
    build: .
    container_name: agstatyba-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
      - VITE_STRIPE_SECRET_KEY=${VITE_STRIPE_SECRET_KEY}
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./build:/app/build
      - ./.svelte-kit:/app/.svelte-kit
      - ./static:/app/static
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: agstatyba-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
